### ISSUE TITLE
Compose a list of movies for the game

### ISSUE THREAD

**Issue by nbuytaert1** [nbuytaert1/apex-movie-game#12]
Sixty movies have been collected so far.

```sql
select *
from mg_movies;
```

A TMDB URL contains all the information you need. For example: https://www.themoviedb.org/movie/550-fight-club
550 is the TMDB_ID and Fight Club is the movie title.

**Comment by JeroenPleysier** [comment]
Added 60 movies for a total of 120

**Comment by nbuytaert1** [comment]
Jan VR also added some movies.
We now have a collection of 200 movies.
