### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by nbuytaert1** [nbuytaert1/apex-movie-game#13]
An AWS instance will be used as production environment.
URL: http://contribute.be/movie-game (?)

**Comment by fhuysmans** [comment]
Do we already have a great name for this great game?
I'll make sure the url will work.
I was wondering wether to do a redirect or to embed the apex app in an iframe in the page.
Is the latter feasible?  It makes it cleaner for the end-user.

Thx

**Comment by nbuytaert1** [comment]
I'm actually still looking for a creative name for the game...

It is possible to work with an iFrame on the Contribute website. It's not a bad idea to test the iFrame approach of course, but I don't think it will break the game.

**Comment by nbuytaert1** [comment]
The URL will be http://contribute.be/moviepick/

**Comment by JeroenPleysier** [comment]
I still get an ERR-7620 Could not determine workspace for application (1010).
ORA-01403: no data found page, just to let you know.

**Comment by nbuytaert1** [comment]
I'll deploy the game tomorrow on that URL.
I have submitted the game to the jury in the mean time, so everything is fine ;-)
